class Report {
  final String id, type,
      title,
      date,
      loop,
      rate,
      absent,
      studentNumber,
      studentName,
      save,
      revison,
      nSave,
      nRevison,
      nTajweed,
      nTafseer,
      nMeaning,
      nAdaa,
      nBehaviour,
      nMowadaba;

  const Report(
      {
        required this.id,
        required this.type,
      required this.title,
      required this.date,
      required this.loop,
      required this.rate,
      required this.absent,
      required this.studentNumber,
      required this.studentName,
      required this.save,
      required this.revison,
      required this.nSave,
      required this.nRevison,
      required this.nTajweed,
      required this.nTafseer,
      required this.nMeaning,
      required this.nAdaa,
      required this.nBehaviour,
      required this.nMowadaba});
  factory Report.fromJson(Map<String, dynamic> json,String docID) {
    return Report(
        id:docID,
        type: json['type'],
        title: json['title'],
        date: json['date'],
        loop: json['loop'],
        rate: json['rate'],
        absent: json['absent'],
        studentNumber: json['studentNumber'],
        studentName: json['studentName'],
        save: json['save'],
        revison: json['revison'],
        nSave: json['nSave'],
        nRevison: json['nRevison'],
        nTajweed: json['nTajweed'],
        nTafseer: json['nTafseer'],
        nMeaning: json['nMeaning'],
        nAdaa: json['nAdaa'],
        nBehaviour: json['nBehaviour'],
        nMowadaba: json['nMowadaba']);
  }
  Map<String, dynamic> toJson() => {
        'type': type,
        'title': title,
        'date': date,
        'loop': loop,
        'rate': rate,
        'absent': absent,
        'studentNumber': studentNumber,
        'studentName': studentName,
        'save': save,
        'revison': revison,
        'nSave': nSave,
        'nRevison': nRevison,
        'nTajweed': nTajweed,
        'nTafseer': nTafseer,
        'nMeaning': nMeaning,
        'nAdaa': nAdaa,
        'nBehaviour': nBehaviour,
        'nMowadaba': nMowadaba
      };
}
