// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyAy-j4UpKqOC_1saIoPDTE-wo5-QtNGRDg",
      authDomain: "kutubuk-b6fdb.firebaseapp.com",
      projectId: "kutubuk-b6fdb",
      storageBucket: "kutubuk-b6fdb.appspot.com",
      messagingSenderId: "222482691072",
      appId: "1:222482691072:android:35485c38869d8d295b94e5",
      measurementId: "G-5LR7605BRX");

  static const FirebaseOptions ios = FirebaseOptions(
    authDomain: "kutubuk-b6fdb.firebaseapp.com",
    apiKey: 'AIzaSyBFkFVBsZkUea5jes8rFG6TceyXWwfTPlU',
    appId: '1:222482691072:ios:f9bd2904bb258c025b94e5',
    projectId: "kutubuk-b6fdb",
    messagingSenderId: "222482691072",
    measurementId: "G-5LR7605BRX",
    storageBucket: "kutubuk-b6fdb.appspot.com",
    iosBundleId: 'com.kutubuk.app',
  );
}
